package hengda.haxi.zhangxiang.model

data class Journal02Detail03(
        var id: Int,
        var uuid: String,
        var master_id: Int,
        var name: String,
        var train: String,
        var carriage: String,
        var position: String,
        var date: String,
        var time: String,
        var production_date: String,
        var reason: String,
        var p_ljbs: String,
        var p_gywj: String,
        var component_sn_old: String,
        var component_sn_new: String,
        var p_bjaz: String,
        var operator: String,
        var leader: String,
        var p_bjgnsy: String,
        var qc: String,
        var duty_officer: String,
        var carriage_01: Boolean,
        var carriage_02: Boolean,
        var carriage_03: Boolean,
        var carriage_04: Boolean,
        var carriage_05: Boolean,
        var carriage_06: Boolean,
        var carriage_07: Boolean,
        var carriage_08: Boolean
)
